apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pytorch-job
spec:
  minAvailable: 2
  schedulerName: volcano
  queue: test-queue
  plugins:
    pytorch: [
      "--master=master",
      "--worker=worker",
      "--port=29500", 
    ]
  tasks:
    - replicas: 1
      name: master
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec: &task-spec
          containers:
            - image: ghcr.io/cyril-k/pytorch-llama-cookbook:24.07-0.0.5
              imagePullPolicy: Always
              name: llama-cookbook-finetuning
              command: 
               - /bin/bash
               - -c
               - |
                torchrun \
                  --nnodes=2 \
                  --nproc_per_node=8 \
                  --node_rank=${RANK} \
                  --rdzv_backend=c10d \
                  --rdzv_endpoint=${MASTER_ADDR}:${MASTER_PORT} \
                  --role `hostname -s`: \
                  --tee 3 \
                  finetuning.py \
                  --enable_fsdp \
                  --fsdp_config.pure_bf16 \
                  --use_fast_kernels \
                  --model_name=/workspace/persistent-storage/models/meta-llama--Llama-3.1-8B/ \
                  --batch_size_training=8 \
                  --num_workers_dataloader=4 \
                  --dist_checkpoint_root_folder=/workspace/persistent-storage/ \
                  --samsum_dataset.trust_remote_code=True \
                  --use-wandb
              env:
                - name: NCCL_SOCKET_IFNAME
                  value: "eth0"
                - name: GLOO_SOCKET_IFNAME
                  value: "eth0"
                - name: CUDA_LAUNCH_BLOCKING
                  value: "0"
                - name: WANDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: finetuning-job-secret
                      key: WANDB_API_KEY
                - name: HF_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: finetuning-job-secret
                      key: HF_TOKEN
                - name: HF_DATASETS_TRUST_REMOTE_CODE
                  value: "True"
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /dev/infiniband
                  name: ib
                - mountPath: /workspace/persistent-storage
                  name: persistent-storage
          restartPolicy: OnFailure
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
            - name: ib
              hostPath:
                path: /dev/infiniband
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: external-storage-persistent-volumeclaim
    - replicas: 1
      name: worker
      template:
        spec: *task-spec
